sudo: false
language: rust

rust:
  - 1.33.0
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

# Test with and without the suggestion feature enabled
# See https://github.com/servo/rust-smallvec/blob/master/.travis.yml for guide
script: |
  cargo test --verbose

# To add tests that exclude older rust versions, use the following format
# ([ $TRAVIS_RUST_VERSION = 1.18.0 ] || cargo test --verbose --features suggestions)