sudo: false
language: rust

rust:
  - 1.18.0
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

# Test with and without the suggestion feature enabled
# See https://github.com/servo/rust-smallvec/blob/master/.travis.yml for guide
script: |
  cargo test --verbose &&
  cargo test --verbose --features suggestions