[package]
name = "darling"
version = "0.6.3"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/darling"
documentation = "https://docs.rs/darling/0.6.3"
description = """
A proc-macro library for reading attributes into structs when
implementing custom derives.
"""
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "TedDriggs/darling" }

[dependencies]
darling_core = { version = "=0.6.3", path = "core" }
darling_macro = { version = "=0.6.3", path = "macro" }

[dev-dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.14"

[workspace]
members = ["macro", "core"]
