[package]
name = "darling"
version = "0.8.5"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/darling"
documentation = "https://docs.rs/darling/0.8.5"
description = """
A proc-macro library for reading attributes into structs when
implementing custom derives.
"""
license = "MIT"
readme = "README.md"
exclude = ["/.travis.yml", "/publish.sh"]

[badges]
travis-ci = { repository = "TedDriggs/darling" }

[dependencies]
darling_core = { version = "=0.8.5", path = "core" }
darling_macro = { version = "=0.8.5", path = "macro" }

[dev-dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15.26"

[features]
diagnostics = [ "darling_core/diagnostics" ]
suggestions = [ "darling_core/suggestions" ]

[workspace]
members = ["macro", "core"]
