rust-ffsend-0.2.44-1.fc31.src[package]
name = "darling_core"
version = "0.9.0"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/darling"
description = """
Helper crate for proc-macro library for reading attributes into structs when
implementing custom derives. Use https://crates.io/crates/darling in your code.
"""
license = "MIT"

[features]
diagnostics = []
suggestions = ["strsim"]

[dependencies]
ident_case = "1.0.0"
proc-macro2 = "0.4.26"
quote = "0.6"
syn = { version = "0.15.26", features = ["full", "extra-traits"] }
fnv = "1.0.6"
strsim = { version = "0.9", optional = true }
