[package]
name = "darling_core"
version = "0.6.1"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/darling"
description = """
Helper crate for proc-macro library for reading attributes into structs when
implementing custom derives. Use https://crates.io/crates/darling in your code.
"""
license = "MIT"

[features]
# temporary hack to make Racer autocomplete work; it requires a 3-part version
# number and doesn't allow for any feature declarations.
default = ["syn/full"]

[dependencies]
ident_case = "1.0.0"
proc-macro2 = "0.3"
quote = "0.5"
syn = { version = "0.13", features = ["extra-traits"] }
fnv = "1.0.6"